apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-chrn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-gibd-tenant/appstudio/dc-metro-map-chrn@sha256:25f765cca04347949ddb2fd2bc7ae0a23938fc087b8527ee4c4f52f263e42024
        name: my-nodejs
        resources: {}
status: {}
